<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SDL3-CS" Version="3.4.2" />
    <PackageReference Include="SDL3-CS.Native" Version="3.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Thermal\Thermal.csproj" />
    <ProjectReference Include="..\GreenPng\GreenPng.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/**/*" />
  </ItemGroup>

</Project>
